[package]
name = "aspirina"
version = "0.1.0"
edition = "2021"
description = "A modular neural network library with matrix operations and backpropagation"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
